// components/team/TeamOnboardingBanner.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Pencil, UserPlus, CalendarPlus } from 'lucide-react';

import { cn } from '@/lib/utils';
import {
  useGetTeamQuery,
  useGetTeamMembersQuery,
} from '@/lib/store/api/teamsApi';
import { useListMyEventsQuery } from '@/lib/store/api/eventsApi';
import { useAppSelector } from '@/lib/store/hooks';
import { selectUser } from '@/lib/store/slices/authSlice';
import { InviteMemberDialog } from '@/components/team/InviteMemberDialog';

interface TeamOnboardingBannerProps {
  accountId: string;
  teamId: string;
}

// ============================================================
// STEP TYPE — discriminated union so `href` is required on link
// ============================================================

type Step = {
  number: number;
  icon: typeof Pencil;
  title: string;
  description: string;
  action: string;
} & (
  | { kind: 'link'; href: string }
  | { kind: 'button'; onClick: () => void }
);

// ============================================================
// COMPONENT
// ============================================================

/**
 * Shows a "get started" card at the top of the team dashboard when the
 * team is brand-new — never renamed, only one member, no events. Hides
 * for the rest of the session when dismissed, and disappears for good
 * as soon as the user makes any progress.
 */
export function TeamOnboardingBanner({
  accountId,
  teamId,
}: TeamOnboardingBannerProps) {
  const user = useAppSelector(selectUser);

  const { data: team } = useGetTeamQuery(teamId, { skip: !teamId });
  const { data: membersData } = useGetTeamMembersQuery(
    { teamId, params: { limit: 1, offset: 0 } },
    { skip: !teamId },
  );
  const { data: eventsData } = useListMyEventsQuery(
    { page: 1, page_size: 1, scope: 'team', team_id: teamId },
    { skip: !teamId },
  );

  const [inviteOpen, setInviteOpen] = useState(false);
  const [dismissed, setDismissed] = useState(false);

  // Read session-only dismissal flag.
  useEffect(() => {
    if (!teamId) return;
    const key = `onboarding_dismissed_${teamId}`;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setDismissed(sessionStorage.getItem(key) === '1');
  }, [teamId]);

  // While data is loading, stay silent — don't flash a banner.
  if (!team || !membersData || !eventsData) return null;
  if (dismissed) return null;

  // Determine whether the team is "brand new".
  const autoGeneratedName = team.display_name ?? '';
  const firstName = (user?.name ?? '').split(' ')[0];
  const patternsToMatch = [
    `Team ${firstName}`,
    `${firstName}'s Personal Team`,
    `${user?.name}'s Personal Team`,
  ];
  const wasRenamed = !patternsToMatch.includes(autoGeneratedName);

  const memberCount = membersData.total ?? 0;
  const hasTeammates = memberCount > 1;

  const eventCount = eventsData?.data?.total ?? 0;
  const hasEvents = eventCount > 0;

  // Any progress → hide the banner entirely.
  if (wasRenamed || hasTeammates || hasEvents) return null;

  const handleDismiss = () => {
    sessionStorage.setItem(`onboarding_dismissed_${teamId}`, '1');
    setDismissed(true);
  };

  const teamBase = `/dashboard/${accountId}/${teamId}`;

  const steps: Step[] = [
    {
      number: 1,
      icon: Pencil,
      title: 'Rename your team',
      description: 'Give it a name that reads like yours.',
      action: 'Set up',
      kind: 'link',
      href: `${teamBase}/settings#general`,
    },
    {
      number: 2,
      icon: UserPlus,
      title: 'Invite teammates',
      description: 'Bring the people who run events with you.',
      action: 'Invite',
      kind: 'button',
      onClick: () => setInviteOpen(true),
    },
    {
      number: 3,
      icon: CalendarPlus,
      title: 'Create an event',
      description: 'Publish your first session and share the link.',
      action: 'Start',
      kind: 'link',
      href: `${teamBase}/events/new`,
    },
  ];

  return (
    <>
      <div
        className={cn(
          'relative overflow-hidden rounded-2xl border border-border/70',
          'bg-gradient-to-br from-primary/[0.04] via-card to-card',
          'shadow-sm',
        )}
      >
        {/* Left accent */}
        <div className="absolute inset-y-0 left-0 w-[3px] bg-primary/70" />

        <div className="px-5 py-5 sm:px-6 sm:py-6">
          {/* Header */}
          <div className="mb-5">
            <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary">
              Welcome
            </p>
            <h2 className="mt-1 text-lg font-semibold tracking-tight text-foreground">
              Get started
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Three quick steps to make this team your own.
            </p>
          </div>

          {/* Steps */}
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-3">
            {steps.map((step) => {
              const Icon = step.icon;

              const inner = (
                <div
                  className={cn(
                    'group flex h-full flex-col rounded-xl border border-border/70 bg-background/60 p-4 text-left',
                    'transition-colors hover:border-primary/40 hover:bg-background',
                  )}
                >
                  {/* Row 1: number badge + icon */}
                  <div className="mb-3 flex items-center justify-between">
                    <span className="flex h-6 w-6 items-center justify-center rounded-full border border-primary/30 text-[11px] font-semibold text-primary">
                      {step.number}
                    </span>
                    <Icon className="h-4 w-4 text-muted-foreground/70 transition-colors group-hover:text-primary" />
                  </div>

                  {/* Title */}
                  <p className="text-sm font-medium text-foreground">
                    {step.title}
                  </p>

                  {/* Description */}
                  <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                    {step.description}
                  </p>

                  {/* Action */}
                  <span className="mt-4 inline-flex items-center gap-1.5 text-xs font-medium text-primary/90 transition-colors group-hover:text-primary">
                    {step.action}
                    <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-0.5" />
                  </span>
                </div>
              );

              if (step.kind === 'link') {
                return (
                  <Link key={step.number} href={step.href}>
                    {inner}
                  </Link>
                );
              }

              return (
                <button
                  key={step.number}
                  type="button"
                  onClick={step.onClick}
                  className="text-left"
                >
                  {inner}
                </button>
              );
            })}
          </div>

          {/* Dismiss */}
          <div className="mt-4 flex justify-end">
            <button
              type="button"
              onClick={handleDismiss}
              className="text-xs text-muted-foreground transition-colors hover:text-foreground"
            >
              Dismiss
            </button>
          </div>
        </div>
      </div>

      <InviteMemberDialog
        open={inviteOpen}
        onOpenChange={setInviteOpen}
        teamId={teamId}
      />
    </>
  );
}